apps/loginregister/urls.py
from django.conf.urls import url
from . import views
app_name = 'loginregister'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^validate$', views.validate, name='validate'),
    url(r'^logout$', views.logout, name='logout'),
    url(r'^deleteAllTestRecords$', views.deleteAllTestRecords, name='deleteAll')
]

beltreview/urls.py
from django.conf.urls import url, include
# from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.review.urls', namespace='review')),
    url(r'^', include('apps.loginregister.urls', namespace='login')),
    # url(r'^admin/', admin.site.urls),
]

apps/loginregister/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
import re
import bcrypt
EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')

class UserManager(models.Manager):
    def regvalidate(self, form_data):
        errors = []
        if len(form_data['name']) < 2 or not form_data['name'].isalpha():
            errors.append(
                'Name must include no fewer than two ' +
                'characters and include alphabetic characters only.'
            )
        if len(form_data['alias']) < 6 or not form_data['alias'].isalnum():
            errors.append(
                'Alias must include no few than six alphanumeric ' +
                'characters, of which at least one must be a letter.'
            )
        if not EMAIL_REGEX.match(form_data['email']):
            errors.append(
                'Please enter a valid email address.'
            )
        if len(form_data['password']) < 8:
            errors.append('Password must include at least eight characters.')
        if form_data['password'] != form_data['confirm']:
            errors.append('Passwords do not match.')
        return errors
    def logvalidate(self, form_data):
        results = {
            'errors': False,
            'id': None,
        }
        print 'Diamine Ox Blood'
        try:
            founduser = User.objects.get(email=form_data['email'])
            print founduser.password
            print form_data['password']
            if founduser.password == bcrypt.hashpw(
                    form_data['password'].encode(),
                    founduser.password.encode()
            ):
                results['id'] = founduser.id
                print 'Baystate Blue'
                return results
            else:
                results['errors'] = True
            return results
        except:
            print "Noodler's Dark Matter"
            results['errors'] = True
        return results

# Create your models here.
class User(models.Model):
    name = models.CharField(max_length=100)
    alias = models.CharField(max_length=30)
    email = models.CharField(max_length=100)
    password = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = UserManager()

apps/loginregister/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import bcrypt
from django.core.urlresolvers import reverse
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.messages import get_messages
from .models import User
# Create your views here.
def index(request):
    # print 'Black Swan in Australian Roses'
    return render(request, 'loginregister/index.html')

def validate(request):
    # print '54th Massachusetts'
    if request.method == 'POST':
        if request.POST['submit'] == 'register':
            userobject = {
                'name': request.POST['reg_name'],
                'alias': request.POST['reg_alias'],
                'email': request.POST['reg_email'],
                'password': request.POST['reg_password'],
                'confirm': request.POST['reg_confirm']
            }
            print userobject
            errors = User.objects.regvalidate(userobject)
            if errors:
                for message in errors:
                    messages.error(request, message, extra_tags='register')
            else:
                newuser = User.objects.create(
                    name=userobject['name'],
                    alias=userobject['alias'],
                    email=userobject['email'].lower(),
                    password=(
                        bcrypt.hashpw(userobject['password'].encode(),
                                      bcrypt.gensalt())
                    )
                )
                request.session['id'] = newuser.id
                return redirect(reverse('review:home'))
        elif request.POST['submit'] == 'login':
            print 'almost there!'
            logobject = {
                'email': request.POST['log_email'],
                'password': request.POST['log_password']
            }
            login = User.objects.logvalidate(logobject)
            if login['errors']:
                print 'aw yeah'
                messages.error(
                    request, 'Login failed; please try again.',
                    extra_tags='login')
            else:
                request.session['id'] = login['id']
                return redirect(reverse('review:home'))
    # for each in get_messages(request):
    #     print each.extra_tags
    #     print each
    return redirect('/')

def logout(request):
    for sessionkey in request.session.keys():
        del request.session[sessionkey]
    return render(request, 'loginregister/logout.html')

def deleteAllTestRecords(request):
    User.objects.all().delete()
    print 'All user records deleted.'
    return redirect('/')

apps/loginregister/templates/loginregister/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8'>
    <title>Welcome</title>
  </head>
  <body>
    <h1>Welcome!</h1>
    <form action="{% url 'login:validate' %}" method="POST">
    {% csrf_token %}
      <fieldset name="register" value="register">
        <legend>Register</legend>
        <label for="reg_name">Name:</label>
        <input type="text" id="reg_name" name="reg_name">
        <label for="alias">Alias:</label>
        <input type="text" id="reg_alias" name="reg_alias">
        <label for="reg_email">Email:</label>
        <input type="text" id="reg_email" name="reg_email">
        <label for="reg_password">Password:</label>
        <input type="password" id="reg_password" name="reg_password">
        <p>*Password should be at least eight characters.</p>
        <label for="reg_confirm">Confirm Password:</label>
        <input type="password" id="reg_confirm" name="reg_confirm">
        <button type="submit" name="submit" value="register">Register</button>
      </fieldset>
      <fieldset name="login" value="login">
        <legend>Login</legend>
        <label for="log_email">Email:</label>
        <input type="text" id="log_email" name="log_email">
        <label for="log_password">Password:</label>
        <input type="password" id="log_password" name="log_password">
        <button type="submit" name="submit" value="login">Login</button>
      </fieldset>
    </form>
    {% for message in messages %}
      <p>{{ message }}</p>
    {% endfor %}
  </body>
</html>

apps/loginregister/templates/loginregister/logout.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8'>
    <title>Logged Out</title>
  </head>
  <body>
    <h2>You have successfully logged out.</h2>
    <a href="{% url 'login:index' %}">Click here to return to the login page.</a>
  </body>
</html>