apps/loginregister/urls.py
from django.conf.urls import url
from . import views
app_name = 'loginregister'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^validate$', views.validate, name='validate'),
    url(r'^logout$', views.logout, name='logout'),
    url(r'^deleteAllTestRecords$', views.deleteAllTestRecords, name='deleteAll')
]

apps/review/urls.py
from django.conf.urls import url
from . import views
app_name = 'review'
urlpatterns = [
    url(r'^books$', views.home, name='home'),
    url(r'^books/add$', views.addbook, name='addbook'),
    url(r'^books/(?P<bookid>\d+)$', views.thisbook, name='thisbook'),
    url(r'^users/(?P<userid>\d+)$', views.thisuser, name='thisuser'),
    url(r'^books/addbooknow$', views.addbooknow, name='add_book_now'),
    url(r'^books/addreview$', views.addreview, name='addreview'),
    url(r'^books/deletereview/(?P<reviewid>\d+)$', views.deletereview,
        name='deletereview'),
]

beltreview/urls.py
from django.conf.urls import url, include
# from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.review.urls', namespace='review')),
    url(r'^', include('apps.loginregister.urls', namespace='login')),
    # url(r'^admin/', admin.site.urls),
]

apps/review/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.db.models import Q
from ..loginregister.models import User
class ReviewManager(models.Manager):
    def three_recent(self):
        recent = Review.objects.all().order_by('-created_at')[:3]
        return recent
    def these_reviews(self, bookid):
        these = Review.objects.filter(book__id=bookid)
        return these
    def validate_review(self, content, rating):
        if len(content) > 4 and int(rating) in range(1, 6):
            return True
        else:
            return False
class BookManager(models.Manager):
    def validate_book(self, form_data):
        for each in form_data:
            print form_data[each]
        if (
                len(form_data['title']) > 0 and
                len(form_data['content']) > 4 and
                int(form_data['rating']) in range(1,6)
        ):
            return True
        else:
            return False
    def check_for_existing_book(self, book):
        return (
            Book.objects.filter(title=book['title'])
            .filter(
                Q(author__name=book['authorlist']) |
                Q(author__name=book['newauthor']))).first()
class AuthorManager(models.Manager):
    def check_author(self, authorname):
        print authorname
        if Author.objects.filter(name=authorname):
            result = {
                'exists': True,
                'author': Author.objects.get(name=authorname)
            }
            return result
        else:
            result = {'exists': False}
            return result
class Author(models.Model):
    name = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = AuthorManager()
class Book(models.Model):
    title = models.CharField(max_length=255)
    author = models.ForeignKey(Author)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = BookManager()
class Review(models.Model):
    creator = models.ForeignKey(User)
    book = models.ForeignKey(Book)
    content = models.TextField(max_length=2000)
    rating = models.SmallIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = ReviewManager()

apps/review/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import bcrypt
from django.core.urlresolvers import reverse
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import Author, Book, Review
from ..loginregister.models import User
# Create your views here.
def home(request):
    # print 'Heart of Darkness'
    print User.objects.get(id=request.session['id']).alias
    context = {
        'recent_reviews': Review.objects.three_recent(),
        'alias': User.objects.get(id=request.session['id']).alias,
        'books': Book.objects.all()
    }
    return render(request, 'review/home.html', context)

def addbook(request):
    context = {'authors': Author.objects.all()}
    return render(request, 'review/addbook.html', context)

def thisbook(request, bookid):
    context = {
        'id': request.session['id'],
        'thisbook': Book.objects.get(id=bookid),
        'reviews': Review.objects.all().filter(book__id=bookid),
    }
    return render(request, 'review/book.html', context)

def thisuser(request, userid):
    context = {
        'user': User.objects.get(id=userid),
        'review_count': Review.objects.filter(
            creator__id=userid).count(),
        'user_booklist': Book.objects.filter(
            review__creator__id=userid).distinct,
    }
    return render(request, 'review/user.html', context)

def addbooknow(request):
    if request.method == 'POST':
        if request.POST['newauthor']:
            print 'yup'
            result = Author.objects.check_author(request.POST['newauthor'])
            if result['exists']:
                add_author = False
                author = result['author']
                print 'exists'
            else:
                add_author = True
                print 'will add author'
        else:
            if request.POST['authorlist']:
                result = Author.objects.check_author(request.POST['authorlist'])
                print result
                if result['exists']:
                    add_author = False
                    author = result['author']
                else:
                    print 'was it this error?'
                    messages.error(
                        request, 'Something has gone wrong with ' +
                        'your request; try again!'
                    )
                    return redirect(reverse('review:addbook'))
        book_object = {
            'title': request.POST['title'],
            'content': request.POST['content'],
            'rating': request.POST['rating'],
            'authorlist': request.POST['authorlist'],
            'newauthor': request.POST['newauthor']
        }
        # print book_object['content']
        if not Book.objects.validate_book(book_object):
            print 'problem!'
            messages.error(
                request, 'Something has gone wrong with your request;' +
                ' try again!'
            )
            return redirect(reverse('review:addbook'))
        book_exists = Book.objects.check_for_existing_book(book_object)
        if book_exists:
            print book_exists
            book_id = book_exists.id
            book = book_exists
            creator = User.objects.get(id=request.session['id'])
            Review.objects.create(content=request.POST['content'],
                                  rating=int(request.POST['rating']),
                                  book=book,
                                  creator=creator)
            return redirect(reverse('review:thisbook', kwargs={'bookid': book_id}))
        if add_author:
            # print 'yess now we add'
            author = Author.objects.create(name=request.POST['newauthor'])
        new_book = Book.objects.create(
            title=request.POST['title'],
            author=author
        )
        new_book_id = new_book.id
        creator = User.objects.get(id=request.session['id'])
        Review.objects.create(content=request.POST['content'],
                              rating=int(request.POST['rating']),
                              book=new_book,
                              creator=creator)
        return redirect(reverse('review:thisbook', kwargs={'bookid': new_book_id}))
    return redirect(reverse('review:addbook'))

def addreview(request):
    if request.method == 'POST':
        book_id = request.POST['bookid']
        if Review.objects.validate_review(request.POST['content'],
                                          request.POST['rating']):
            Review.objects.create(content=request.POST['content'],
                                  rating=int(request.POST['rating'],),
                                  book=Book.objects.get(id=request.POST
                                                        ['bookid']),
                                  creator=User.objects.get(id=request.session
                                                           ['id']))
    return redirect(reverse('review:thisbook', kwargs={'bookid': book_id}))

def deletereview(request, reviewid):
    this_review = Review.objects.get(id=reviewid)
    if this_review.creator.id == request.session['id']:
        Review.objects.get(id=reviewid).delete()
    return redirect(reverse('review:thisbook',
                            kwargs={'bookid': this_review.book.id}))

apps/review/templates/review/addbook.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8'>
    <title>Add Book and Review</title>
  </head>
  <body>
    <div id="wrapper">
      <a href="{% url 'review:home' %}">Home</a>
      <a href="{% url 'login:logout' %}">Logout</a>
      <form action="{% url 'review:add_book_now' %}" method="POST">
      {% csrf_token %}
        <h2>Add a New Book Title and a Review:</h2>
        <label for="title">Book Title:</label>
        <input type="text" name="title" id="title">
        <label for="author">Author:</label>
        <div id="author">
          <label for="authorlist">Choose from the list:</label>
          <select name="authorlist" id="authorlist">
            {% for each in authors %}
              <option value="{{ each.name }}">{{ each.name }}</option>
            {% endfor %}
          </select>
          <label for="newauthor">Or add a new author:</label>
          <input type="text" id="newauthor" name="newauthor">
        </div>
        <label for="content">Review:</label>
        <textarea name="content" id="content" cols="50" rows="6"></textarea>
        <label for="rating">Rating:</label>
        <input id="rating" name="rating" type="number" value="5" step="1" min="1" max="5">
        <button type="submit" name="submit" id="submit">Add Book and Review</button>
      </form>
      {% for message in messages %}
        <p>{{ message }}</p>
      {% endfor %}
    </div>
  </body>
</html>

apps/review/templates/review/book.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8'>
    <title>Reviews for {{ thisbook.title }}</title>
  </head>
  <body>
    <div id="wrapper">
      <a href="{% url 'review:home' %}">Home</a>
      <a href="{% url 'login:logout' %}">Logout</a>
      <h2>{{ thisbook.title }}</h2>
      <h4>Author: {{ thisbook.author.name }}</h4>
      <h2>Reviews:</h2>
      {% for review in reviews %}
        <p>Rating:
          {% for i in 'x'|rjust:review.rating %}
            <span>* </span>
          {% endfor %}</p>
        <p><a href="{% url 'review:thisuser' userid=review.creator.id %}">{{ review.creator.alias }}</a> says:
        <span class="review">{{ review.content }}</span></p>
        <p class="footnote">Posted on {{ review.created_at|date:'F j, Y' }}</p>
        {% if review.creator.id == request.session.id %}
          <a href="{% url 'review:deletereview' reviewid=review.id %}">Delete this Review</a>
        {% endif %}
      {% endfor %}
      <form action="{% url 'review:addreview' %}" method="POST">
      {% csrf_token %}
        <h3>Add a Review:</h3>
        <label for="content">Add a Review:</label>
        <input type="hidden" name="bookid" value={{ thisbook.id }}>
        <textarea name="content" id="content" cols="25" rows="6"></textarea>
        <label for="rating">Rating:</label>
        <input name="rating" id="rating" value="5" type="number" step="1" min="1" max="5">
        <button type="submit" name="submit">Submit Review</button>
      </form>
    </div>
  </body>
</html>

apps/review/templates/review/home.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8'>
    <title>Books Home</title>
    {% load staticfiles %}
  </head>
  <body>
    <div id="wrapper">
      <h1>Welcome, {{ alias }}!</h1>
      <a href="{% url 'review:addbook' %}">Add Book and Review</a>
      <a href="{% url 'login:logout' %}">Logout</a>
      <div id="recent">
        <h2>Recent Book Reviews:</h2>
        {% for review in recent_reviews %}
          <h3><a href="{% url 'review:thisbook' bookid=review.book.id %}">{{ review.book.title }}
          </a></h3>
          <p>Rating:
            {% for i in 'x'|rjust:review.rating %}
              <span>* </span>
            {% endfor %}</p>
          <p><a href="{% url 'review:thisuser' userid=review.creator.id %}">{{ review.creator.alias }}
          </a> says: <span class="review">{{ review.content }}</span></p>
          <p class="footnote">Posted on {{ review.created_at|date:'F j, Y' }}</p>
        {% endfor %}
      </div>
      <div id="others">
        <h2>All Books with Reviews:</h2>
        <ul class="scrollable">
          {% for book in books %}
            <li><a href="{% url 'review:thisbook' bookid=book.id %}">{{ book.title }}</a></li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </body>
</html>

apps/review/templates/review/user.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8'>
    <title>{{ user.alias }}'s Reviews</title>
  </head>
  <body>
    <div id="wrapper">
      <a href="{% url 'review:home' %}">Home</a>
      <a href="{% url 'review:addbook' %}">Add Book and Review</a>
      <a href="{% url 'login:logout' %}">Logout</a>
      <h1>User Alias: {{ user.alias }}</h1>
      <h2>Name: {{ user.name }}</h2>
      <h2>Email: {{ user.email }}</h2>
      <h2>Total Reviews: {{ review_count }}</h2>
      <h2>Posted Reviews on the following books:</h2>
      <ul>
        {% for book in user_booklist %}
          <li><a href="{% url 'review:thisbook' bookid=book.id %}">{{ book.title }}</a></li>
        {% endfor %}
      </ul>
    </div>
  </body>
</html>